const test=require('node:test'),assert=require('node:assert/strict');
const {model}=require('./native-row-overlay.js');
const sha='a'.repeat(64);
function fixture(){return {metadata:{document_id:'d',page_no:1,source_sha256:sha,native_row:{document_id:'d',page_no:1,source_sha256:sha,fields:[{bbox_pt:[10,20,30,40],header:'Subject',text:'A'},{bbox_pt:[50,20,60,40],header:'Result',text:'3 UG/L'}]}},manifest:{document_id:'d',page_no:1,source_sha256:sha,size_px:[200,100],mappings:{fitz_unrotated_to_display:[1,0,0,1,0,0],display_to_asset_px:[1,0,0,1,0,0]}},selection:{column_index:1}};}
test('subject and queried cell keep separate exact rectangles',()=>{const f=fixture(),boxes=model(f.metadata,f.manifest,f.selection);assert.deepEqual(boxes[1].bbox_normalized,[.25,.2,.3,.4]);assert.equal(boxes[1].role,'value');assert.equal(boxes[0].role,'subject');});
test('90-degree rotated original uses server matrix rather than guessed orientation',()=>{const f=fixture();f.manifest.size_px=[100,200];f.manifest.mappings.fitz_unrotated_to_display=[0,1,-1,0,100,0];assert.deepEqual(model(f.metadata,f.manifest,f.selection)[1].bbox_normalized,[.6,.25,.8,.3]);});
test('crop offsets and rendering scale both apply',()=>{const f=fixture();f.manifest.mappings.display_to_asset_px=[2,0,0,2,-10,-20];assert.deepEqual(model(f.metadata,f.manifest,f.selection)[1].bbox_normalized,[.45,.2,.55,.6]);});
test('wrong source page or document prevents misleading highlight',()=>{for(const key of ['source_sha256','document_id','page_no']){const f=fixture();f.manifest[key]='wrong';assert.throws(()=>model(f.metadata,f.manifest,f.selection));}});
test('invalid index matrix or field bounds are rejected',()=>{const f=fixture();assert.throws(()=>model(f.metadata,f.manifest,{column_index:true}));f.manifest.mappings.fitz_unrotated_to_display=[0,0,0,0,0,0];assert.throws(()=>model(f.metadata,f.manifest,f.selection));const g=fixture();g.metadata.native_row.fields[1].bbox_pt=[50,20,500,40];assert.throws(()=>model(g.metadata,g.manifest,g.selection));});
